--- hot-babe-0.2.2/Makefile	2004-12-04 16:49:30.000000000 -0700
+++ hot-babe-0.2.2/Makefile.new	2021-11-22 16:04:58.407808261 -0700
@@ -1,20 +1,20 @@
 # where to install this program
-PREFIX := /usr/local
+PREFIX := /usr
 VERSION := 0.2.2
 
 # optimization cflags
-CFLAGS += -O2 -Wall -g `pkg-config gdk-2.0 gdk-pixbuf-2.0  --cflags` -DPREFIX=\"$(PREFIX)\" -DVERSION=\"$(VERSION)\"
+CFLAGS += -Wall `pkg-config gdk-2.0 gdk-pixbuf-2.0  --cflags` -DPREFIX=\"$(PREFIX)\" -DVERSION=\"$(VERSION)\"
 
 OBJS = hot-babe.o loader.o
 CC = gcc
 LIBS = `pkg-config gdk-2.0 gdk-pixbuf-2.0  --libs`
 
-DOC = ChangeLog NEWS TODO LICENSE CONTRIBUTORS copyright config.example
+DOC = ChangeLog NEWS TODO CONTRIBUTORS config.example
 
 all: hot-babe
 
 hot-babe: $(OBJS)
-	$(CC) -o hot-babe $(OBJS) $(LIBS)
+	$(CC) $(CFLAGS) $(OBJS) $(LIBS) -o hot-babe $(LDFLAGS)
 
 clean:
 	rm -f hot-babe *.o
@@ -24,10 +24,8 @@
 	install -m 0755 hot-babe $(DESTDIR)$(PREFIX)/bin
 	install -d $(DESTDIR)$(PREFIX)/share/hot-babe/hb01
 	install -m 0644 hb01/* $(DESTDIR)$(PREFIX)/share/hot-babe/hb01
-	install -d $(DESTDIR)$(PREFIX)/share/doc/hot-babe
-	install -m 0644 $(DOC) $(DESTDIR)$(PREFIX)/share/doc/hot-babe
-	install -d $(DESTDIR)$(PREFIX)/share/man/man1
-	install -m 0644 hot-babe.1 $(DESTDIR)$(PREFIX)/share/man/man1
+	install -d $(DESTDIR)$(PREFIX)/share/doc/hot-babe-$(VERSION)
+	install -m 0644 $(DOC) $(DESTDIR)$(PREFIX)/share/doc/hot-babe-$(VERSION)
 	install -d $(DESTDIR)$(PREFIX)/share/pixmaps
 	install -m 0644 hot-babe.xpm $(DESTDIR)$(PREFIX)/share/pixmaps
 
