#!/bin/sh
#
# This file is sourced by Xsession(5), not executed.
BOINC_USER=boinc
#
# If xhost installed, use it to give access to the X server to any
# process from the same user on the local host.
# Unlike other uses of xhost, this is safe since the kernel can check
# the actual owner of the calling process.

if type xhost >/dev/null 2>&1; then
  id -u $BOINC_USER >/dev/null 2>&1 && xhost +SI:localuser:$BOINC_USER || :
fi
